version: '3'

services:
  jscam:
    build: ./dev
#    sysctls:
#      - kern.maxfiles=5242880
#      - kern.maxfilesperproc=524288
    image: jscam
    stdin_open: true
    tty: true
    #entrypoint: /my_entrypoint.sh
    network_mode: "host"
    privileged: true
#    restart: unless-stopped
#    ports:
#      - "127.0.0.1:9091:9091"
    volumes:
     - "./src:/home/project/src"
     - "./src/node_modules:/home/project/src/node_modules"
     - "./src/deps:/home/project/src/deps"
     - "/etc/group:/etc/group:ro"
     - "/etc/sudoers:/etc/sudoers:ro"
     - "/etc/shadow:/etc/shadow:ro"
     - "/etc/passwd:/etc/passwd:ro"
