version: '3'

services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile.dev
    image: jscam
    stdin_open: true
    tty: true
    #entrypoint: /my_entrypoint.sh
    network_mode: "host"
    privileged: false
    volumes:
     - "./src/jscam:/home/project/src/jscam"
     - "./src/node_modules:/home/project/src/jscam/node_modules"
     - "./src/deps:/home/project/src/deps"
     - "/etc/group:/etc/group:ro"
     - "/etc/sudoers:/etc/sudoers:ro"
     - "/etc/shadow:/etc/shadow:ro"
     - "/etc/passwd:/etc/passwd:ro"

